spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatis_plus?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456

    druid:
      aop-patterns: com.mytest.boot.*  #监控SpringBean
      filters: stat,wall     # 底层开启功能，stat（sql监控），wall（防火墙）

      stat-view-servlet: # 配置监控页功能
        enabled: true
        login-username: root
        login-password: 123456
#        resetEnable: false

      web-stat-filter: # 监控web
        enabled: true
        urlPattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'


      filter:
        stat: # 对上面filters里面的stat的详细配置
          slow-sql-millis: 1000
          logSlowSql: true
          enabled: true
        wall:
          enabled: true
#          config:
#            drop-table-allow: false
mybatis:
  mapper-locations: classpath:mapper/*.xml

#  下面两个不能同时存在,建议用2
#  config-location: classpath:mybatis/   全局配置文件
  configuration:
    map-underscore-to-camel-case: true